In [ ]:
#creating numpy?n-d arrays 
import numpy as np


In [24]:
arr1=np.array([1,2,3,4,5])
arr1


array([1, 2, 3, 4, 5])

In [ ]:
#2d array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#zero matrix
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#singular matrix
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#identity matrix
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#
arr6=np.arange(10)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr7=np.arange(5,21)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr8=np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [21]:
arr8=np.linspace(1,10,6)
arr8

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [ ]:
#copy
arr8=np.linspace(1,10,6) 
arr9=arr8.copy() 
arr9

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [26]:
#some important attributes
#1 shape
arr1=np.array([1,2,3,4,5])
print(arr1.shape)
arr2=np.array([[1,2,3],[4,5,6]])
arr2.shape

(5,)


(2, 3)

In [ ]:
#3d matrix
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr9)
print(arr9.shape)
arr9.ndim #to know dimnjesional of matrix 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


3

In [ ]:
#size
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9.size



8

In [34]:
#item size
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9.itemsize

8

In [35]:
#dtype
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9.dtype

dtype('int64')

In [ ]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9.astype("float") #convertdata type 

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [ ]:
#numpy array7 vs python list
# SIZE
import numpy as np
lista = range(100)
arr11=np.arange(100)
import sys
print(sys.getsizeof(87)*len(lista),"this is the size of list a") #get size gives the size 

print(arr11.itemsize*arr11.size)


2800 this is the size of list a
800


In [ ]:
import time
x=range(10000000)
y=range(10000000,2000000)
start_time=time.time()#gives current time 

c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

0.002040386199951172


In [8]:
x=np.arange(10000000)
y=np.arange (10000000,20000000)

start_time=time.time()
c=x+y 

print(time.time()-start_time)

0.03794574737548828
